---
layout: default
title: PELM - Emacs Lisp Manager
excerpt: a emacs lisp manager 
---


* What is  the PELM?

  PELM  - a "literate" Emacs Lisp Manager  for Emacs (24.0 and greater).

  What's the P means? the P  can be one of Personal or Public (if you like it)
  I hope every body like it, but maybe not. any fork is welcome!

** Install
*** Basic install 
- clone source code from github to .emacs.d
  
#+BEGIN_SRC sh
$ cd ~
$ git clone http://github.com/eggckaer/pelm.git .emacs.d
$ cd .emacs.d
$ git submodule init
$ git submodule update

#+END_SRC

#+results:

- clone source code to some where in your folder and ln it 
  for example, you want clone to ~/pelm
  
#+BEGIN_SRC sh
$ git clone http://github.com/eggcaker/pelm.git ~/pelm 
$ ln -s ~/pelm ~/.emacs.d 
$ cd ~/pelm
$ git submodule init
$ git submodule update
#+END_SRC
*** Byte compile (optional but recommented)
#+BEGIN_EXAMPLE
C-u 0 M-x byte-recompile-directory
#+END_EXAMPLE

** Customize 
   after you clone the PELM, check the init.el, you can add your own code 
   in 2 files :
- pre-init-local.org 
   the PELM loaded  it before load plugins but after the pre-init.el

- post-init-local.org 
  the PELM loaded after all plugins  

   both of them ignore by git, so can add some experimental code.

** Package Manager

Thanks [[http://tapoueh.org/][Dimitri Fontaine]] built the [[https://github.com/dimitri/el-get][ el-get]]! I use it to install some third-part packages:
- el-get
- swtich-window
- auto-compleate-mode
- psvn 
- fuzzy
- yasnippet
- color-theme
- smex
- magit
- goto-last-change 

** License

   check out the [[https://github.com/eggcaker/pelm/blob/master/LICENSE][LICENSE]] file 


** Help out!

   fork me and make a pull request.


** Authors
- eggcaker <eggcaker@gmail.com>


